DROP TABLE COUNTRY;
DROP TABLE CUSTOMER;
DROP TABLE DEPARTMENT;
DROP TABLE EMPLOYEE;
DROP TABLE EMPLOYEE_PROJECT;
DROP TABLE JOB;
DROP TABLE PROJ_DEPT_BUDGET;
DROP TABLE PROJECT;
DROP TABLE SALARY_HISTORY;
DROP TABLE SALES;

DROP TABLE KONTRAGENT;
DROP TABLE ORDER;
